# Generated by Django 4.1.7 on 2023-03-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circulares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('intro', models.CharField(max_length=255)),
                ('anexo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Circular',
                'verbose_name_plural': 'Circulares',
            },
        ),
    ]
