# Generated by Django 4.1.7 on 2023-03-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circulares',
            name='intro',
        ),
    ]
